DATASET_INFO_PATH = "data/dataset_info.pt"
STATE_DICT_PATH = "model/state_dict.pt"
DATASET_FILE_PATHS = ["data/allabcwrepeats_parsed.txt"]

MODEL_HIDDEN_SIZE = 64
MODEL_EMBEDDING_SIZE = 64
MODEL_EMBEDDINGS_DROPOUT = 0.3
MODEL_LSTM_DROPOUT = 0.5
MODEL_NUM_HIDDEN_LAYERS = 1
